### ISSUE TITLE
Pls. provide sample request and response for the list of all APIs

### ISSUE THREAD

**Issue by diwakarang** [team-swag-dhst/llm-agents-berkeley#2]

**Comment by tomcotter7** [comment]
Yep, sure:

API 1: Image segmentation

Request:
```json
{
    "image": bytes,
    "clicks": [[100, 100], [0, 200]],
    "previouslySent": bool
}
```

Response:
```json
{
    "masked_image": bytes
}
```

API 2: LLM 
Request:
```json
{
   "image": bytes,
   "masked_image": bytes,
   "clicks": list[list[int]]
   "text": str,
}
```

Response:
**Streaming back text**

The request doesn't have to contain all inputs, it'll probably be [`image`, `masked_image`], [`image`, `clicks`], [`text`], [`image`, `text`] as the four options.

**Comment by tomcotter7** [comment]
Does that make sense @diwakarang ?

**Comment by diwakarang** [comment]
Link to API-v1
https://b677-82-31-174-83.ngrok-free.app/docs

**Comment by diwakarang** [comment]
Closing this , as scope is completed
